version: "3.9"

services:
  web1:
    image: 9f749042d6c7
    ports:
      - "5000:5000"
    networks:
      - my_network
    environment:
      - FLASK_ENV=development
      - FLASK_CONFIG=development
      - SQLALCHEMY_DATABASE_URI=postgresql://myuser:mypassword@database/mydatabase
  web2:
    image: 9f749042d6c7
    ports:
      - "5001:5000"
    networks:
      - my_network
    environment:
      - FLASK_ENV=development
      - FLASK_CONFIG=development
      - SQLALCHEMY_DATABASE_URI=postgresql://myuser:mypassword@database/mydatabase

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1

    networks:
      - my_network

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
